# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: misollar-service/misollar_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'misollar-service/misollar_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'misollar-service/misollar_service.proto\x12\x10misollar_service\"&\n\x10\x43ompleteResponse\x12\x12\n\nsrc_phrase\x18\x01 \x03(\t\"I\n\x0fMisollarRequest\x12\x12\n\nsrc_phrase\x18\x01 \x01(\t\x12\x10\n\x08src_lang\x18\x02 \x01(\t\x12\x10\n\x08tgt_lang\x18\x03 \x01(\t\"\"\n\x04Span\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"\x85\x02\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07sent_id\x18\x02 \x01(\t\x12\x10\n\x08src_lang\x18\x03 \x01(\t\x12\x12\n\nsrc_phrase\x18\x04 \x01(\t\x12\x14\n\x0csrc_sentence\x18\x05 \x01(\t\x12)\n\tsrc_spans\x18\x06 \x03(\x0b\x32\x16.misollar_service.Span\x12\x10\n\x08tgt_lang\x18\x07 \x01(\t\x12\x12\n\ntgt_phrase\x18\x08 \x01(\t\x12\x14\n\x0ctgt_sentence\x18\t \x01(\t\x12)\n\ttgt_spans\x18\n \x03(\x0b\x32\x16.misollar_service.Span\x12\x0e\n\x06source\x18\x0b \x01(\t\"<\n\x10MisollarResponse\x12(\n\x04hits\x18\x01 \x03(\x0b\x32\x1a.misollar_service.Document2\xce\x01\n\x0fMisollarService\x12[\n\x12get_misollar_query\x12!.misollar_service.MisollarRequest\x1a\".misollar_service.MisollarResponse\x12^\n\x15get_misollar_complete\x12!.misollar_service.MisollarRequest\x1a\".misollar_service.CompleteResponseB\x1bZ\x19genproto/misollar_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'misollar_service.misollar_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031genproto/misollar_service'
  _globals['_COMPLETERESPONSE']._serialized_start=61
  _globals['_COMPLETERESPONSE']._serialized_end=99
  _globals['_MISOLLARREQUEST']._serialized_start=101
  _globals['_MISOLLARREQUEST']._serialized_end=174
  _globals['_SPAN']._serialized_start=176
  _globals['_SPAN']._serialized_end=210
  _globals['_DOCUMENT']._serialized_start=213
  _globals['_DOCUMENT']._serialized_end=474
  _globals['_MISOLLARRESPONSE']._serialized_start=476
  _globals['_MISOLLARRESPONSE']._serialized_end=536
  _globals['_MISOLLARSERVICE']._serialized_start=539
  _globals['_MISOLLARSERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
