# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from misollar_service import misollar_service_pb2 as misollar__service_dot_misollar__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in misollar_service/misollar_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MisollarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_misollar_query = channel.unary_unary(
                '/misollar_service.MisollarService/get_misollar_query',
                request_serializer=misollar__service_dot_misollar__service__pb2.MisollarRequest.SerializeToString,
                response_deserializer=misollar__service_dot_misollar__service__pb2.MisollarResponse.FromString,
                _registered_method=True)
        self.get_misollar_complete = channel.unary_unary(
                '/misollar_service.MisollarService/get_misollar_complete',
                request_serializer=misollar__service_dot_misollar__service__pb2.MisollarRequest.SerializeToString,
                response_deserializer=misollar__service_dot_misollar__service__pb2.CompleteResponse.FromString,
                _registered_method=True)


class MisollarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_misollar_query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_misollar_complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MisollarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_misollar_query': grpc.unary_unary_rpc_method_handler(
                    servicer.get_misollar_query,
                    request_deserializer=misollar__service_dot_misollar__service__pb2.MisollarRequest.FromString,
                    response_serializer=misollar__service_dot_misollar__service__pb2.MisollarResponse.SerializeToString,
            ),
            'get_misollar_complete': grpc.unary_unary_rpc_method_handler(
                    servicer.get_misollar_complete,
                    request_deserializer=misollar__service_dot_misollar__service__pb2.MisollarRequest.FromString,
                    response_serializer=misollar__service_dot_misollar__service__pb2.CompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'misollar_service.MisollarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('misollar_service.MisollarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MisollarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_misollar_query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/misollar_service.MisollarService/get_misollar_query',
            misollar__service_dot_misollar__service__pb2.MisollarRequest.SerializeToString,
            misollar__service_dot_misollar__service__pb2.MisollarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_misollar_complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/misollar_service.MisollarService/get_misollar_complete',
            misollar__service_dot_misollar__service__pb2.MisollarRequest.SerializeToString,
            misollar__service_dot_misollar__service__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
