# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query-service/query_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'query-service/query_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!query-service/query_service.proto\x12\rquery_service\"F\n\x0cQueryRequest\x12\x12\n\nsrc_phrase\x18\x01 \x01(\t\x12\x10\n\x08src_lang\x18\x02 \x01(\t\x12\x10\n\x08tgt_lang\x18\x03 \x01(\t\"\"\n\x04Span\x12\r\n\x05start\x18\x01 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x05\"\xef\x01\n\x08\x44ocument\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07sent_id\x18\x02 \x01(\t\x12\x10\n\x08src_lang\x18\x03 \x01(\t\x12\x12\n\nsrc_phrase\x18\x04 \x01(\t\x12\x14\n\x0csrc_sentence\x18\x05 \x01(\t\x12&\n\tsrc_spans\x18\x06 \x03(\x0b\x32\x13.query_service.Span\x12\x10\n\x08tgt_lang\x18\x07 \x01(\t\x12\x12\n\ntgt_phrase\x18\x08 \x01(\t\x12\x14\n\x0ctgt_sentence\x18\t \x01(\t\x12&\n\ttgt_spans\x18\n \x03(\x0b\x32\x13.query_service.Span\"6\n\rQueryResponse\x12%\n\x04hits\x18\x01 \x03(\x0b\x32\x17.query_service.Document2V\n\x0cQueryService\x12\x46\n\tget_query\x12\x1b.query_service.QueryRequest\x1a\x1c.query_service.QueryResponseB\x13Z\x11\x61pp/query_serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_service.query_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021app/query_service'
  _globals['_QUERYREQUEST']._serialized_start=52
  _globals['_QUERYREQUEST']._serialized_end=122
  _globals['_SPAN']._serialized_start=124
  _globals['_SPAN']._serialized_end=158
  _globals['_DOCUMENT']._serialized_start=161
  _globals['_DOCUMENT']._serialized_end=400
  _globals['_QUERYRESPONSE']._serialized_start=402
  _globals['_QUERYRESPONSE']._serialized_end=456
  _globals['_QUERYSERVICE']._serialized_start=458
  _globals['_QUERYSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
